name: Dependabot

on:
  pull_request:
    # Enable Dependabot PRs to trigger this workflow
    if: github.actor == 'dependabot[bot]'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test:run

    - name: Build project
      run: npm run build

    - name: Enable Dependabot automerging
      if: github.event_name == 'pull_request'
      run: |
        gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
